#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom ade4 meanfacwt
#' @importFrom ade4 randtest
#' @importFrom ade4 varfacwt
#' @importFrom adegraphics s.arrow
#' @importFrom adegraphics s.class
#' @importFrom dplyr across
#' @importFrom dplyr filter
#' @importFrom dplyr sym
#' @importFrom ggplot2 .data
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 annotate
#' @importFrom ggplot2 arrow
#' @importFrom ggplot2 coord_fixed
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 expansion
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 geom_col
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_label
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_polygon
#' @importFrom ggplot2 geom_ribbon
#' @importFrom ggplot2 geom_segment
#' @importFrom ggplot2 geom_smooth
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggplot_build
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_color_discrete
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_size
#' @importFrom ggplot2 scale_size_area
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_x_discrete
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_linedraw
#' @importFrom ggplot2 theme_void
#' @importFrom ggplot2 vars
#' @importFrom ggplot2 waiver
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom ggrepel geom_text_repel
#' @importFrom mvtnorm dmvnorm
#' @importFrom stats AIC
#' @importFrom stats anova
#' @importFrom stats as.formula
#' @importFrom stats cor
#' @importFrom stats dnorm
#' @importFrom stats formula
#' @importFrom stats lm.wfit
#' @importFrom stats model.frame
#' @importFrom stats model.matrix
#' @importFrom stats predict
#' @importFrom stats rbinom
#' @importFrom stats rnorm
#' @importFrom stats rpois
#' @importFrom stats runif
#' @importFrom tidyselect all_of
## usethis namespace: end
NULL
